import NumDetect.Basic
import General.MatrixAnalysis.RowDeletion
import Mathlib.Analysis.CStarAlgebra.Matrix

/-! Generalized Hankel/Toeplitz, Vandermonde, segmented, and MUSIC objects. -/

set_option autoImplicit false
set_option backward.isDefEq.respectTransparency false

open Matrix WithLp
open scoped BigOperators

namespace LeanNumDetect
namespace NumDetect

noncomputable section

/-- Steering vector for an ordered finite frequency family. -/
def steeringVector {d : ℕ} {ι : Type*} (frequency : ι → Point d)
    (y : Point d) : ι → ℂ :=
  fun i => Complex.exp (Complex.I * (dot (frequency i) y : ℂ))

/-- Generalized Vandermonde matrix `𝓥_Γ(𝓧)`. -/
def generalizedVandermonde {d n : ℕ} {ι : Type*}
    (frequency : ι → Point d) (node : Fin n → Point d) :
    Matrix ι (Fin n) ℂ :=
  fun i j => steeringVector frequency (node j) i

/-- Generalized Hankel matrix for a function whose domain is an arbitrary set `𝓓`,
including the manuscript's hypothesis `𝓐 + 𝓑 ⊆ 𝓓`. -/
def generalizedHankelOn {d : ℕ} {ι κ : Type*}
    (rowFrequency : ι → Point d) (columnFrequency : κ → Point d)
    (domain : Set (Point d)) (f : domain → ℂ)
    (hadd : ∀ i j, rowFrequency i + columnFrequency j ∈ domain) :
    Matrix ι κ ℂ :=
  fun i j => f ⟨rowFrequency i + columnFrequency j, hadd i j⟩

/-- Generalized Toeplitz matrix for a function whose domain is an arbitrary set `𝓓`,
including the manuscript's hypothesis `𝓐 - 𝓑 ⊆ 𝓓`. -/
def generalizedToeplitzOn {d : ℕ} {ι κ : Type*}
    (rowFrequency : ι → Point d) (columnFrequency : κ → Point d)
    (domain : Set (Point d)) (f : domain → ℂ)
    (hsub : ∀ i j, rowFrequency i - columnFrequency j ∈ domain) :
    Matrix ι κ ℂ :=
  fun i j => f ⟨rowFrequency i - columnFrequency j, hsub i j⟩

/-- Generalized Hankel matrix generated by `f` and two ordered frequency families. -/
def generalizedHankel {d : ℕ} {ι κ : Type*}
    (rowFrequency : ι → Point d) (columnFrequency : κ → Point d)
    (f : Point d → ℂ) : Matrix ι κ ℂ :=
  fun i j => f (rowFrequency i + columnFrequency j)

/-- Generalized Toeplitz matrix generated by `f` and two ordered frequency families. -/
def generalizedToeplitz {d : ℕ} {ι κ : Type*}
    (rowFrequency : ι → Point d) (columnFrequency : κ → Point d)
    (f : Point d → ℂ) : Matrix ι κ ℂ :=
  fun i j => f (rowFrequency i - columnFrequency j)

/-- The manuscript's Hankel-type Vandermonde factorization. -/
def hankelVandermondeFactor {d n : ℕ} {ι κ : Type*}
    [Fintype (Fin n)] [DecidableEq (Fin n)]
    (rowFrequency : ι → Point d) (columnFrequency : κ → Point d)
    (μ : AtomicMeasure d n) : Matrix ι κ ℂ :=
  generalizedVandermonde rowFrequency μ.node *
    Matrix.diagonal μ.amplitude *
    (generalizedVandermonde columnFrequency μ.node)ᵀ

/-- The manuscript's Toeplitz-type Vandermonde factorization. -/
def toeplitzVandermondeFactor {d n : ℕ} {ι κ : Type*}
    [Fintype (Fin n)] [DecidableEq (Fin n)]
    (rowFrequency : ι → Point d) (columnFrequency : κ → Point d)
    (μ : AtomicMeasure d n) : Matrix ι κ ℂ :=
  generalizedVandermonde rowFrequency μ.node *
    Matrix.diagonal μ.amplitude *
    (generalizedVandermonde columnFrequency μ.node)ᴴ

/-- A matrix admits either one of the two generalized Vandermonde decompositions. -/
def AdmitsGeneralizedVandermondeDecomposition {d : ℕ} {ι κ : Type*}
    (rowFrequency : ι → Point d) (columnFrequency : κ → Point d)
    (A : Matrix ι κ ℂ) : Prop :=
  ∃ (n : ℕ) (μ : AtomicMeasure d n),
    A = hankelVandermondeFactor rowFrequency columnFrequency μ ∨
    A = toeplitzVandermondeFactor rowFrequency columnFrequency μ

/-- Multi-index set `{0, …, s}^d` for the contiguous construction. -/
abbrev UniformIndex (d s : ℕ) := Fin d → Fin (s + 1)

/-- Physical row frequency `(Ω/s) α` of the contiguous Vandermonde matrix. -/
def uniformFrequency (d s : ℕ) (Ω : ℝ) (α : UniformIndex d s) : Point d :=
  fun k => Ω / s * α k

/-- The contiguous multidimensional Vandermonde matrix `V₁`. -/
def uniformVandermonde {d n : ℕ} (s : ℕ) (Ω : ℝ)
    (node : Fin n → Point d) : Matrix (UniformIndex d s) (Fin n) ℂ :=
  generalizedVandermonde (uniformFrequency d s Ω) node

/-- The queried GHM `GH(s)` on the scaled grid from the manuscript. -/
def uniformMeasurementMatrix {d : ℕ} (s : ℕ) (Ω : ℝ)
    (Y : Point d → ℂ) : Matrix (UniformIndex d s) (UniformIndex d s) ℂ :=
  fun α β => Y fun k => Ω / s * ((α k : ℝ) + (β k : ℝ) - s)

/-- Phase-shifted diagonal in the contiguous GHM factorization. -/
def uniformPhaseAmplitude {d n : ℕ} (Ω : ℝ) (μ : AtomicMeasure d n) :
    Fin n → ℂ :=
  fun j => μ.amplitude j *
    Complex.exp (-Complex.I * (Ω * ∑ k, μ.node j k : ℝ))

/-- Noiseless contiguous GHM `V₁ Σ V₁ᵀ`. -/
def uniformNoiselessMatrix {d n : ℕ} (s : ℕ) (Ω : ℝ)
    (μ : AtomicMeasure d n) :
    Matrix (UniformIndex d s) (UniformIndex d s) ℂ :=
  uniformVandermonde s Ω μ.node *
    Matrix.diagonal (uniformPhaseAmplitude Ω μ) *
    (uniformVandermonde s Ω μ.node)ᵀ

/-- One row-coordinate of the segmented index set. -/
abbrev SegmentedCoordinateIndex (m r : ℕ) := Fin (r + 1) × Fin (m + 1)

/-- The Cartesian product `Λ^d`, with its canonical block/offset ordering. -/
abbrev SegmentedIndex (d m r : ℕ) := Fin d → SegmentedCoordinateIndex m r

/-- Integer frequency `D s + h` represented as a real vector. -/
def segmentedFrequency (d m r D : ℕ) (α : SegmentedIndex d m r) : Point d :=
  fun k => (D * (α k).1 + (α k).2 : ℕ)

/-- Maximum segmented frequency `Ω = rD + m`. -/
def segmentedCutoff (m r D : ℕ) : ℕ :=
  r * D + m

/-- Number of one-dimensional segmented indices `L = (r+1)(m+1)`. -/
def segmentedLength (m r : ℕ) : ℕ :=
  (r + 1) * (m + 1)

/-- The segmented multidimensional Vandermonde matrix `V₁`. -/
def segmentedVandermonde {d n : ℕ} (m r D : ℕ)
    (node : Fin n → Point d) :
    Matrix (SegmentedIndex d m r) (Fin n) ℂ :=
  generalizedVandermonde (segmentedFrequency d m r D) node

/-- Column Vandermonde factor in the symmetric segmented GHM construction. -/
def segmentedColumnVandermonde {d n : ℕ} (m r D : ℕ)
    (node : Fin n → Point d) :
    Matrix (SegmentedIndex d m r) (Fin n) ℂ :=
  generalizedVandermonde (segmentedFrequency d m r D) node

/-- The segmented measurement matrix `GH(m,r,D)`. -/
def segmentedMeasurementMatrix {d : ℕ} (m r D : ℕ)
    (Y : Point d → ℂ) :
    Matrix (SegmentedIndex d m r) (SegmentedIndex d m r) ℂ :=
  fun α β => Y fun k =>
    segmentedFrequency d m r D α k + segmentedFrequency d m r D β k -
      segmentedCutoff m r D

/-- Phase-shifted diagonal in the segmented GHM factorization. -/
def segmentedPhaseAmplitude {d n : ℕ} (m r D : ℕ) (μ : AtomicMeasure d n) :
    Fin n → ℂ :=
  fun j => μ.amplitude j *
    Complex.exp (-Complex.I *
      ((segmentedCutoff m r D : ℝ) * ∑ k, μ.node j k : ℝ))

/-- Noiseless segmented GHM `V₁ Σ V₁ᵀ`. -/
def segmentedNoiselessMatrix {d n : ℕ} (m r D : ℕ)
    (μ : AtomicMeasure d n) :
    Matrix (SegmentedIndex d m r) (SegmentedIndex d m r) ℂ :=
  segmentedVandermonde m r D μ.node *
    Matrix.diagonal (segmentedPhaseAmplitude m r D μ) *
    (segmentedColumnVandermonde m r D μ.node)ᵀ

/-- Spectral/operator norm induced by Euclidean norms. -/
def matrixSpectralNorm {ι κ : Type*} [Fintype ι] [Fintype κ]
    [DecidableEq κ] (A : Matrix ι κ ℂ) : ℝ :=
  ‖(Matrix.toEuclideanLin.trans LinearMap.toContinuousLinearMap) A‖

/-- Full column rank of a finite matrix. -/
def HasFullColumnRank {ι κ : Type*} [Fintype κ]
    (A : Matrix ι κ ℂ) : Prop :=
  Function.Injective A.mulVecLin

/-- A matrix whose columns are an orthonormal basis of the left noise space of `A`. -/
def IsLeftNoiseSpaceBasis {ι κ q : Type*}
    [Fintype ι] [Fintype κ] [Fintype q] [DecidableEq q]
    (A : Matrix ι κ ℂ) (U₂ : Matrix ι q ℂ) : Prop :=
  U₂ᴴ * U₂ = 1 ∧
  LinearMap.range U₂.mulVecLin = LinearMap.ker Aᴴ.mulVecLin

/-- An orthonormal basis of left singular vectors, ordered by decreasing
singular value. It is obtained by diagonalizing `A Aᴴ`. -/
noncomputable def leftSingularBasis {ι κ : Type*}
    [Fintype ι] [Fintype κ] [DecidableEq ι] [DecidableEq κ]
    (A : Matrix ι κ ℂ) :
    OrthonormalBasis (Fin (Fintype.card ι)) ℂ (EuclideanSpace ℂ ι) :=
  A.toEuclideanLin.adjoint.isSymmetric_adjoint_comp_self.eigenvectorBasis
    finrank_euclideanSpace

/-- The span of the left singular vectors after the first `signalRank`
vectors. This is the fixed-rank noise subspace used by MUSIC for both exact
and perturbed data matrices. -/
noncomputable def trailingLeftSingularSubspace {ι κ : Type*}
    [Fintype ι] [Fintype κ] [DecidableEq ι] [DecidableEq κ]
    (A : Matrix ι κ ℂ) (signalRank : ℕ) :
    Submodule ℂ (EuclideanSpace ℂ ι) :=
  Submodule.span ℂ
    (Set.range fun j :
      {j : Fin (Fintype.card ι) // signalRank ≤ (j : ℕ)} =>
        leftSingularBasis A j.1)

/-- Unit-normalized row-frequency steering vector. -/
def normalizedSteering {d : ℕ} {ι : Type*} [Fintype ι]
    (frequency : ι → Point d) (y : Point d) : ι → ℂ :=
  (‖toLp 2 (steeringVector frequency y)‖ : ℂ)⁻¹ • steeringVector frequency y

/-- MUSIC noise-space correlation `R(y) = ‖U₂* a(y)‖₂`. -/
def noiseSpaceCorrelation {d : ℕ} {ι q : Type*}
    [Fintype ι] [Fintype q]
    (frequency : ι → Point d) (U₂ : Matrix ι q ℂ) (y : Point d) : ℝ :=
  ‖toLp 2 (U₂ᴴ *ᵥ normalizedSteering frequency y)‖

/-- MUSIC correlation formed from the trailing left singular subspace after a
fixed number of signal singular vectors. -/
noncomputable def rankNoiseSpaceCorrelation
    {d : ℕ} {ι κ : Type*}
    [Fintype ι] [Fintype κ] [DecidableEq ι] [DecidableEq κ]
    (frequency : ι → Point d) (A : Matrix ι κ ℂ)
    (signalRank : ℕ) (y : Point d) : ℝ :=
  ‖(trailingLeftSingularSubspace A signalRank).starProjection
      (toLp 2 (normalizedSteering frequency y))‖

/-- Uniform distance between two MUSIC correlation functions. -/
def correlationUniformDistance {d : ℕ} (R₁ R₂ : Point d → ℝ) : ℝ :=
  sSup (Set.range fun y => |R₁ y - R₂ y|)

end

end NumDetect
end LeanNumDetect
