import General.Probability.ComplexL1WeakNet
import Mathlib.Algebra.Order.BigOperators.Ring.Finset
import Mathlib.Algebra.BigOperators.Fin

/-!
# Entropy of causal atomic-approximation prefixes

The first-crossing mask at level `k` reads only the approximation words
through that level. The finite prefix family has exactly `(4N+1)` raised
to the total word length as its cardinality. Geometrically increasing word
lengths therefore give the desired entropy at the current scale, without
any lookahead refinement factor.
-/

set_option autoImplicit false
set_option backward.isDefEq.respectTransparency false
open scoped BigOperators

namespace LeanNumDetect.BoundedRieszConcentration

/-- The four signed complex coordinate atoms, together with the zero atom. -/
abbrev ComplexAtomicAlphabet (N : ℕ) := Option (Fin N × Fin 4)

/-- One empirical atomic approximation word. -/
abbrev ComplexAtomicWord (N L : ℕ) := Fin L → ComplexAtomicAlphabet N

/-- A finite family of atomic approximation words, with possibly different
lengths at its levels. -/
abbrev ComplexAtomicPrefix (N : ℕ) {ℓ : ℕ} (L : Fin ℓ → ℕ) :=
  ∀ j, ComplexAtomicWord N (L j)

theorem complexAtomicPrefix_card (N : ℕ) {ℓ : ℕ} (L : Fin ℓ → ℕ) :
    Fintype.card (ComplexAtomicPrefix N L) = (4 * N + 1) ^ (∑ j, L j) := by
  classical
  simp only [ComplexAtomicPrefix, ComplexAtomicWord, ComplexAtomicAlphabet, Fintype.card_pi,
    Fintype.card_option, Fintype.card_prod, Fintype.card_fin, Nat.mul_comm N 4,
    Finset.prod_const, Finset.card_univ, Fintype.card_fin]
  exact Finset.prod_pow_eq_pow_sum Finset.univ L (4 * N + 1)

/-- The total word length through level `k` is at most twice its final
geometric word length. -/
theorem geometricPrefix_sum_length_le (L₀ k : ℕ) :
    (∑ j : Fin (k + 1), L₀ * 4 ^ j.val) ≤ 2 * L₀ * 4 ^ k := by
  induction k with
  | zero => simp; omega
  | succ k ih =>
    rw [Fin.sum_univ_castSucc]
    simp only [Fin.val_castSucc, Fin.val_last, pow_succ]
    apply (Nat.add_le_add_right ih _).trans
    ring_nf
    omega

/-- Exact logarithmic entropy of the canonical prefix family. -/
theorem complexAtomicPrefix_log_card (N : ℕ) {ℓ : ℕ} (L : Fin ℓ → ℕ) :
    Real.log (2 * (Fintype.card (ComplexAtomicPrefix N L) : ℝ)) =
      Real.log 2 + (∑ j, (L j : ℝ)) * Real.log (4 * (N : ℝ) + 1) := by
  rw [complexAtomicPrefix_card, Nat.cast_pow,
    Real.log_mul (by norm_num : (2 : ℝ) ≠ 0) (by positivity), Real.log_pow]
  simp only [Nat.cast_sum, Nat.cast_add, Nat.cast_mul, Nat.cast_ofNat, Nat.cast_one]

/-- The causal-prefix entropy is bounded at its current scale. -/
theorem geometricPrefix_log_card_le (N L₀ k : ℕ) :
    Real.log (2 * (Fintype.card (ComplexAtomicPrefix N
      (fun j : Fin (k + 1) => L₀ * 4 ^ j.val)) : ℝ)) ≤
      Real.log 2 + (2 * (L₀ : ℝ) * 4 ^ k) * Real.log (4 * (N : ℝ) + 1) := by
  rw [complexAtomicPrefix_log_card]
  apply add_le_add le_rfl
  apply mul_le_mul_of_nonneg_right
  · exact_mod_cast geometricPrefix_sum_length_le L₀ k
  · exact Real.log_nonneg (by have h := Nat.cast_nonneg (α := ℝ) N; linarith)

/-- The final-level first-crossing mask reads only the finite prefix. -/
noncomputable def prefixFirstCrossingMask {κ : Type*} [Fintype κ]
    {N k : ℕ} (L : Fin (k + 1) → ℕ) (r : Fin (k + 1) → ℝ)
    (a : ∀ j, ComplexAtomicWord N (L j) → κ → ℂ)
    (p : ComplexAtomicPrefix N L) : Finset κ := by
  classical
  exact Finset.univ.filter fun i =>
    r (Fin.last k) ≤ ‖a (Fin.last k) (p (Fin.last k)) i‖ ∧
      ∀ j : Fin (k + 1), j < Fin.last k → ‖a j (p j) i‖ < r j

/-- A family of masks generated by prefixes has no more members than the
prefix words themselves. -/
theorem prefixFirstCrossingMask_family_card_le {κ : Type*} [Fintype κ] [DecidableEq κ]
    {N k : ℕ} (L : Fin (k + 1) → ℕ) (r : Fin (k + 1) → ℝ)
    (a : ∀ j, ComplexAtomicWord N (L j) → κ → ℂ) :
    (Finset.univ.image (prefixFirstCrossingMask L r a)).card ≤
      (4 * N + 1) ^ (∑ j, L j) := by
  classical
  exact (Finset.card_image_le (f := prefixFirstCrossingMask L r a) (s := Finset.univ)).trans_eq
    (by simpa only [Finset.card_univ] using complexAtomicPrefix_card N L)

end LeanNumDetect.BoundedRieszConcentration
