import RandSamp.FixedSupport
import General.Probability.RestrictedQuadraticMoments

/-!
# Full Fourier signals and relative Gram energies

The signal in the full frequency space carries the same normalization as the
manuscript's full Gram matrix. These identities expose every normalization
factor needed when a restricted sampling theorem is applied to Fourier signals.
-/

set_option autoImplicit false
set_option backward.isDefEq.respectTransparency false

open Matrix WithLp
open scoped BigOperators InnerProductSpace

namespace LeanNumDetect.RandSamp

open FiniteMatrixSampling

noncomputable section

/-- The normalized Fourier signal generated by a node tuple and coefficients. -/
def fullFourierSignal {s : ℕ} (M : ℕ) (Y : Fin s → ℝ)
    (z : EuclideanSpace ℂ (Fin s)) : EuclideanSpace ℂ (Fin (M + 1)) :=
  toLp 2 (fun k => (Real.sqrt ((M + 1 : ℕ) : ℝ) : ℂ)⁻¹ *
    ∑ j, fourierRow Y k.val j * ofLp z j)

theorem norm_fullFourierSignal_sq {s : ℕ} (M : ℕ) (Y : Fin s → ℝ)
    (z : EuclideanSpace ℂ (Fin s)) :
    ‖fullFourierSignal M Y z‖ ^ 2 = FiniteMatrixSampling.quadratic (fullGram M Y) z := by
  rw [fullGram, quadratic_fourier_mean, EuclideanSpace.norm_sq_eq]
  change (∑ k : Fin (M + 1),
    ‖(Real.sqrt ((M + 1 : ℕ) : ℝ) : ℂ)⁻¹ *
      ∑ j, fourierRow Y k.val j * ofLp z j‖ ^ 2) = _
  simp_rw [norm_mul, mul_pow, norm_inv, Complex.norm_real,
    Real.norm_eq_abs, abs_of_nonneg (Real.sqrt_nonneg _), inv_pow,
    Real.sq_sqrt (Nat.cast_nonneg (M + 1))]
  rw [← Finset.mul_sum]
  rfl

theorem fullFourierSignal_coordinate_energy {s : ℕ} (M : ℕ)
    (Y : Fin s → ℝ) (z : EuclideanSpace ℂ (Fin s)) (k : Fin (M + 1)) :
    ((M + 1 : ℕ) : ℝ) * ‖fullFourierSignal M Y z k‖ ^ 2 =
      fourierRowEnergy Y k.val (ofLp z) := by
  change ((M + 1 : ℕ) : ℝ) *
    ‖(Real.sqrt ((M + 1 : ℕ) : ℝ) : ℂ)⁻¹ *
      ∑ j, fourierRow Y k.val j * ofLp z j‖ ^ 2 = _
  simp only [norm_mul, mul_pow, norm_inv, Complex.norm_real, Real.norm_eq_abs,
    abs_of_nonneg (Real.sqrt_nonneg _), inv_pow,
    Real.sq_sqrt (Nat.cast_nonneg (M + 1)), fourierRowEnergy]
  rw [← mul_assoc, mul_inv_cancel₀ (by positivity), one_mul]

theorem sampled_fullFourierSignal_energy {s m : ℕ} (M : ℕ)
    (Y : Fin s → ℝ) (z : EuclideanSpace ℂ (Fin s))
    (Ω : Sample (M + 1) m) :
    ((M + 1 : ℕ) : ℝ) / m * ∑ k ∈ Ω.val, ‖fullFourierSignal M Y z k‖ ^ 2 =
      FiniteMatrixSampling.quadratic (sampleMean (fourierPopulation Y) Ω) z := by
  rw [quadratic_fourier_sampleMean, sampledVandermonde_energy, div_eq_mul_inv]
  rw [mul_comm (((M + 1 : ℕ) : ℝ)) (m : ℝ)⁻¹, mul_assoc]
  congr 1
  rw [Finset.mul_sum]
  exact Finset.sum_congr rfl (fun k _ => fullFourierSignal_coordinate_energy M Y z k)

/-- An absolute deviation estimate for the full Fourier signal is exactly
the relative Gram estimate in the manuscript; no deterministic upper bound
or coefficient-space norm is introduced in this conversion. -/
theorem relativeGram_of_fullFourierSignal_deviation {M s m : ℕ}
    (Y : Fin s → ℝ) (z : EuclideanSpace ℂ (Fin s))
    (Ω : Sample (M + 1) m) (ρ : ℝ)
    (h : |((M + 1 : ℕ) : ℝ) / m *
      ∑ k ∈ Ω.val, ‖fullFourierSignal M Y z k‖ ^ 2 -
        ‖fullFourierSignal M Y z‖ ^ 2| ≤ ρ * ‖fullFourierSignal M Y z‖ ^ 2) :
    (1 - ρ) * FiniteMatrixSampling.quadratic (fullGram M Y) z ≤
      FiniteMatrixSampling.quadratic (sampleMean (fourierPopulation Y) Ω) z ∧
    FiniteMatrixSampling.quadratic (sampleMean (fourierPopulation Y) Ω) z ≤
      (1 + ρ) * FiniteMatrixSampling.quadratic (fullGram M Y) z := by
  rw [sampled_fullFourierSignal_energy, norm_fullFourierSignal_sq] at h
  rcases abs_le.mp h with ⟨hlo, hhi⟩
  constructor <;> linarith

/-- The manuscript's relative embedding event for a specified node tuple. -/
def RelativeGramEvent {M s m : ℕ} (Y : Fin s → ℝ) (ρ : ℝ)
    (Ω : Sample (M + 1) m) : Prop :=
  ∀ z : EuclideanSpace ℂ (Fin s),
    (1 - ρ) * FiniteMatrixSampling.quadratic (fullGram M Y) z ≤
      FiniteMatrixSampling.quadratic (sampleMean (fourierPopulation Y) Ω) z ∧
    FiniteMatrixSampling.quadratic (sampleMean (fourierPopulation Y) Ω) z ≤
      (1 + ρ) * FiniteMatrixSampling.quadratic (fullGram M Y) z

/-- Deterministic full-Gram endpoints turn the relative event into exactly
the multiplicative singular-value endpoints stated with the new estimate. -/
theorem singularValueEvent_of_relativeGramEvent {M s m : ℕ} (hs : 0 < s)
    (Y : Fin s → ℝ) {a b ρ : ℝ} (ha : 0 ≤ a) (hρ0 : 0 ≤ ρ) (hρ1 : ρ ≤ 1)
    (Ω : Sample (M + 1) m)
    (hgram : ∀ z : EuclideanSpace ℂ (Fin s),
      a * ‖z‖ ^ 2 ≤ FiniteMatrixSampling.quadratic (fullGram M Y) z ∧
      FiniteMatrixSampling.quadratic (fullGram M Y) z ≤ b * ‖z‖ ^ 2)
    (hrelative : RelativeGramEvent Y ρ Ω) : SingularValueEvent Y a b ρ Ω := by
  apply singularValueEvent_of_sampleMean_bounds hs Y ha hρ1 Ω
  intro z
  constructor
  · calc
      (1 - ρ) * a * ‖z‖ ^ 2 = (1 - ρ) * (a * ‖z‖ ^ 2) := by ring
      _ ≤ (1 - ρ) * FiniteMatrixSampling.quadratic (fullGram M Y) z :=
        mul_le_mul_of_nonneg_left (hgram z).1 (sub_nonneg.mpr hρ1)
      _ ≤ _ := (hrelative z).1
  · calc
      _ ≤ (1 + ρ) * FiniteMatrixSampling.quadratic (fullGram M Y) z := (hrelative z).2
      _ ≤ (1 + ρ) * (b * ‖z‖ ^ 2) :=
        mul_le_mul_of_nonneg_left (hgram z).2 (by linarith)
      _ = (1 + ρ) * b * ‖z‖ ^ 2 := by ring

end

end LeanNumDetect.RandSamp
